# This action redeploys the site on the first of the year to update the copyright date in footer

name: Deploy to Firebase Hosting on first of year
'on':
  schedule:
    - cron: '0 0 1 1 *'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - run: npm install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_653A1 }}'
          channelId: live
          projectId: portfolio-653a1
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
